services:
  mysql:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: Librarian
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/library
      SPRING_DATASOURCE_USERNAME: Librarian
      SPRING_DATASOURCE_PASSWORD: password123
    ports:
      - "8080:8080"

volumes:
  mysql-data: